# remap prefix from 'C-b' to 'C-a'
unbind C-b
set -g prefix `
bind ` send-prefix

set-option -g prefix2 C-a

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key 'Right' if-shell "$is_vim" 'send-keys C-w Right' 'select-pane -R'
bind-key 'Left' if-shell "$is_vim" 'send-keys C-w Left'  'select-pane -L'
#bind-key 'Down' if-shell "$is_vim" 'send-keys C-w Down'  'select-pane -D'
#bind-key 'Up' if-shell "$is_vim" 'send-keys C-w Up'  'select-pane -U'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l


# Set position
set -g status-position bottom

# set refresh interval for status bar
set -g status-interval 60

# center the status bar
set -g status-justify left

# show session, window, pane in left status bar
set -g status-left-length 40
set -g status-left ' #[default]'

# show date and time
set-option -g status-right '%a %Y-%m-%d %H:%M #[fg=green]#S #[default]'

###########################
# Colors (Solarized dark)
# From: https://github.com/seebi/tmux-colors-solarized
###########################

## default statusbar colors
set-option -g status-style bg=colour235,fg=colour136,default

## default window title colors
set-window-option -g window-status-style bg=default,fg=colour244,dim

## active window title colors
set-window-option -g window-status-current-style fg=colour166,bg=default,bright

## pane border
set-option -g pane-border-style fg=colour235
set-option -g pane-active-border-style fg=colour240

## message text
set-option -g message-style bg=colour235,fg=colour166

## pane number display
set-option -g display-panes-active-colour colour33
set-option -g display-panes-colour colour166

## clock
set-window-option -g clock-mode-colour colour64

## bell
set-window-option -g window-status-bell-style fg=colour235,bg=colour160

### Split bar
set -g pane-border-style bg=colour235,fg=colour238
set -g pane-active-border-style bg=colour236,fg=colour167

## Use vi keybindings in copy mode
setw -g mode-keys vi

